version: '3'
services:
  config-service:
    build:
      context: ./config-service
    ports:
      - "8081:8081"
    volumes:
      - config-service-db:/path/to/config-service/data

  profesor-service:
    build:
      context: ./backend-profesor-service
    ports:
      - "8092:8092"
    depends_on:
      - config-service
    volumes:
      - backend-profesor-service-db:/path/to/backend-profesor-service/data
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://profesor-db:5432/Profesores
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=2468

  proyector-service:
    build:
      context: ./backend-proyector-service
    ports:
      - "8093:8093"
    depends_on:
      - backend-profesor-service
    volumes:
      - backend-data-service-db:/path/to/backend-data-service/data
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://proyector-db:5432/Datas
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=2468

  prestamo-service:
    build:
      context: ./backend-prestamo-service
    ports:
      - "8095:8095"
    depends_on:
      - backend-data-service
    volumes:
      - backend-prestamo-service-db:/path/to/backend-prestamo-service/data
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://prestamo-db:5432/Prestamo
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=2468

  devolucion-service:
    build:
      context: ./backend-devolucion-service
    ports:
      - "8094:8094"
    depends_on:
      - backend-prestamo-service
    volumes:
      - backend-devolucion-service-db:/path/to/devolucion-service/data
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://devolucion-db:5432/Devoluciones
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=2468

  gateway-service:
    build:
      context: ./backend-gateway-service
    ports:
      - "8080:8080"
    depends_on:
      - backend-devolucion-service

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - gateway-service

volumes:
  config-service-db:
  profesor-service-db:
  proyector-service-db:
  prestamo-service-db:
  devolucion-service-db:

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16
