spring:
  application:
    name: backend-gateway-service

server:
  port: 8080

eureka:
  client:
    enabled: false

cloud:
  gateway:
    routes:
      - id: backend-data-service
        uri: http://localhost:8081
        predicates:
          - Path=/ingreso-proyectores/**
      - id: backend-profesor-service
        uri: http://localhost:8082
        predicates:
          - Path=/ingreso-profesores/**